[base]
datasets = ["demo"]

[table]

[table.demo]
file_ext = "csv"
data_dir = "screening/local/"
table_name = "SCREENING_LOCAL"
skip_rows = 1

[table.demo.columns]
"Organisation Code" = "VARCHAR"
"Organisation Name" = "VARCHAR"
"Programme" = "VARCHAR"
"Month of Date" = "VARCHAR"
"Cohort Age Range" = "VARCHAR"
"Cohort Description" = "VARCHAR"
"Denominator Name" = "VARCHAR"
"Denominator" = "NUMBER"
"Numerator" = "NUMBER"
"Performance" = "VARCHAR"
"Acceptable" = "VARCHAR"
"Achievable" = "VARCHAR"